changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Performance Improvements 🚀
      labels:
        - performance
    - title: Other Changes
      labels:
        - "*"
